version: '3.8'

services:
  database:
    image: postgres:17
    container_name: patient_info_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - config/.env
    restart: always

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient_info_dev
    ports:
      - 8888:8000
    env_file:
      - config/.env
    volumes: 
      - ./:/home/
      - ./patient_info/static_volume:/home/patient_info/staticfiles
      - ./patient_info/media_volume:/home/patient_info/mediafiles
    # depends_on:
    #   - db
    command: 'sh -c "echo \"Container started\" && while sleep 1; do :; done"'